name: yeko_pointage
description: Yeko Pointage est une application mobile qui permet aux professeurs de prendre la présence de leurs élèves, d'attribuer la participation et de donner des devoirs à faire à la maison. L'application est facile à utiliser et permet aux professeurs de gagner du temps et d'être plus efficaces.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  assets_audio_player: ^3.1.1
  cupertino_icons: ^1.0.2
  data_connection_checker_tv: ^0.3.5-nullsafety
  dio: ^5.3.3
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_native_splash: ^2.3.5
  fpdart: ^1.1.0
  grouped_list: ^5.1.2
  hive: ^2.2.3
  hooks_riverpod: ^2.4.5
  intl: ^0.19.0
  mobile_scanner: ^3.5.4
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.3.0
  shared_preferences: ^2.2.2

dev_dependencies:
  altive_lints: ^1.8.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/fonts/
    - assets/images/
    - assets/json/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
