name: yeko_pointage
description: Yeko Pointage est une application mobile qui permet aux professeurs de prendre la présence de leurs élèves, d'attribuer la participation et de donner des devoirs à faire à la maison. L'application est facile à utiliser et permet aux professeurs de gagner du temps et d'être plus efficaces.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  data_connection_checker_tv: ^0.3.5-nullsafety
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  fpdart: ^1.1.0
  google_ml_kit: ^0.16.3
  hooks_riverpod: ^2.4.5
  internet_connection_checker_plus: ^2.1.0
  intl: ^0.18.1
  riverpod_annotation: ^2.3.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  supabase_flutter: ^1.10.25

dev_dependencies:
  altive_lints: ^1.8.1
  build_runner: ^2.4.6
  custom_lint: ^0.5.6
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.5
  riverpod_lint: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
