name: yeko_pointage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  assets_audio_player: ^3.1.1
  encrypt: ^5.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
    version: ^0.0.0
  flutter_native_splash: ^2.3.13
  fpdart: ^1.1.0
  grouped_list: ^5.1.2
  hooks_riverpod: ^2.4.10
  intl: ^0.18.1
  mobile_scanner: ^4.0.1
  qr_flutter: ^4.1.0
  riverpod_annotation: ^2.3.4
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.3.4

dev_dependencies:
  altive_lints: ^1.9.0
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  custom_lint: ^0.6.2
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.9

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/fonts/
    - assets/images/
    - assets/json/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/DMSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/DMSans-MediumItalic.ttf
          weight: 500
          style: italic
